In [1]:
# installed packages
import pandas as pd
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.tag.perceptron import PerceptronTagger
from nltk import word_tokenize
from nltk.corpus import stopwords
from gensim.models import KeyedVectors
import warnings
import numpy as np
# silencing the warnings
warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)
'''
!pip install nltk
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

!pip install numba
'''

# created packages
import nlp_ops as nlp

In [237]:
def read_data():
    '''
    reads the train and test data
    '''
    train_data = pd.read_csv("Train.csv")
    test_data = pd.read_excel("Test.xlsx")
    return train_data, test_data

In [238]:
def remove_city(row, city_str):
    '''
    This function cleans the city present in job desig column
    '''
    row_list =  [each_word.lower().strip('.').strip().strip('.') for each_word in row.split()]
    for elem in row_list:
        if elem in city_str:
            row_list.remove(elem)
    return ' '.join(row_list)

In [239]:
def clean_data(stitched_data):
    '''
    this function does data cleaning
    '''
    print("Dropping job_type column")
    stitched_data.drop(columns = ['job_type'], inplace = True)
    # Fill missing value, replace '...' from text columns, cleaning location columns
    for col in stitched_data.columns:
        if stitched_data.dtypes[col] == 'object':
            stitched_data[col] = stitched_data[col].str.lower()
            stitched_data[col] = stitched_data[col].str.replace('\(.*\)', '')
            stitched_data[col] = stitched_data[col].str.replace('\.\.\.', '')
            stitched_data[col] = stitched_data[col].fillna(stitched_data[col].mode()[0])
        elif stitched_data.dtypes[col] == 'float64':
            stitched_data[col] = stitched_data[col].fillna(stitched_data[col].mean())

    # remove city name from columns 'job_description', 'job_desig'
    city_name = pd.read_csv('india_city_list.csv')
    city_name = city_name.India_city_list.str.lower().str.strip().replace('.','')
    city_str =' '.join(city_name.to_list())
    stitched_data['job_desig'] = stitched_data['job_desig'].apply(lambda row :remove_city(row, city_str))
    stitched_data['job_description'] = stitched_data['job_description'].apply(lambda row :remove_city(row, city_str))
    stitched_data['location_type'] = ['tier_one' if x in ['mumbai', 'bengaluru', 'delhi','delhi ncr',
                                              'chennai', 'hyderabad','gurgaon', 
                                              'gurugram', 'kolkata'] else 'tier_two' for x in stitched_data['location']] 
    
    stitched_data.drop(columns = ['location'], inplace = True)
    for col in stitched_data.columns:
        if stitched_data.dtypes[col] == 'object':
            stitched_data[col] = stitched_data[col].fillna(stitched_data[col].mode()[0])
        elif stitched_data.dtypes[col] == 'float64':
            stitched_data[col] = stitched_data[col].fillna(stitched_data[col].mean())
    
    return stitched_data

In [240]:
def EDA(stitched_data):
    '''
    creates the EDA report using pyEDA package(self created)
    '''
    from pyEDA.pyEDA.data_profile_2 import profile
    eda_result = profile(stitched_data, get_summary=True,
                get_data_type=True,
                get_skewness={'df':True, 'plot' :False},
                get_kurtosis=None,
                get_missing={'df':True, 'plot' :False},
                get_missing_visual={'df':True, 'plot' :False},
                get_distinct={'df':True, 'plot' :True},
                get_categorical_count={'df':True, 'plot' :False},
                get_numerical_dist_plot={'df':True, 'plot' :False},
                get_numeric_box_plot={'df':True, 'plot' :False},
                get_row_wise_missing={'df':True, 'plot' :False},
                get_correlation={'df':True, 'plot' :False},
                generate_html_report=True)
    return eda_result

In [241]:
def prepare_text_col(word2vec_model, data):
    '''
    this function creates a numerical vector of the preprocessing include :
    filter_tag_pos,  lemmatize_word, stop-words, punctuation removal, number removal
    '''
    print("inside clean data")
    # cleaning Data Text columns - 'job_description', 'job_desig', 'key_skills'
    nlp_cols = ['job_description', 'job_desig', 'key_skills']    
    cleaned_text = nlp.text_clean(word2vec_model, data, nlp_cols)
    for col in nlp_cols:
        cleaned_text[col] = cleaned_text[col].apply(lambda x : abs(np.mean(x)) *10000)
    return cleaned_text

In [242]:
def data_prep(cleaned_data):
    '''
    this function does data preparation including dummy data creation and feature engineering
    '''
    cleaned_data[['exp_lower', 'exp_upper']] = cleaned_data.experience.str.split('-', expand=True)
    cleaned_data['exp_upper'] = cleaned_data.exp_upper.str.split(' ', expand=True)[0]
    cleaned_data.drop(columns = ['experience'], inplace = True)
    # get dummies
    cat_vars = ['location_type']
    for var in cat_vars:
            cat_list='var'+'_'+var
            cat_list = pd.get_dummies(cleaned_data[var], prefix=var)
            cleaned_data = cleaned_data.join(cat_list)
    cleaned_data.drop(columns =['location_type','index'], inplace = True)

In [243]:
def stitch_train_test(train_data, test_data):
    test_data.drop(columns = [clm for clm in test_data.columns if clm not in train_data.columns], inplace = True)
    target = train_data['salary']
    train_data.drop(columns = ['salary'], inplace=True)
    ind = len(train_data)
    stitched_data = train_data.append(test_data).reset_index()
    return stitched_data, target, ind

In [247]:
def find_feat_imp(x, y):
    '''
    calculate feature importance
    '''
    from sklearn.feature_selection import SelectFromModel
    sel = SelectFromModel(RandomForestRegressor(n_estimators = 100))
    sel.fit(x, y)
    selected_feat= x.columns[(sel.get_support())].tolist()
    selected_feat.append('key_skills')
    return selected_feat

In [245]:
def RF_regressor(x_train, y_train, x_test):
    '''
    model building
    '''
    from sklearn.ensemble import RandomForestRegressor
    test_data_cpy = x_test.copy()
    feat = x_train.copy()
    target = y_train['salary_final']
    X,x,Y,y = train_test_split(feat,target,random_state=119)
    print(len(X),len(x),len(Y),len(y))
    regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
    regressor.fit(x, y)
    y_pred = regressor.predict(x)
    
    # Checking RMSE on test set
    from sklearn.metrics import mean_squared_error
    from math import sqrt
    rms = sqrt(mean_squared_error(y, y_pred))
    print('RMSE of RF regressor on test set: {:.2f}'.format(rms))
    
    # training on complete train set
    regressor = RandomForestRegressor(n_estimators = 100, random_state = 0) 
    regressor.fit(feat,target)
    # predicting on test data
    y_test_pred = regressor.predict(x_test.drop(columns = ['salary_final']))
    test_data_cpy['salary'] = y_test_pred
    test_data_cpy['salary'].to_csv("submission_rfr.csv", index = False)  
    print("RF Model Done")
    return test_data_cpy

#### main()

In [252]:
# reading in data
train_data, test_data = read_data()
print("Read Data")
stitched_data, target, ind = stitch_train_test(train_data, test_data)
print("Data Stitched")

# creating visualization and EDA report (Note :  this is a self created package, hence commented this)
#eda_result = EDA(stitched_data.drop(columns = ['index']))

# cleaning the data
cleaned_data = clean_data(stitched_data)

# preparing the data
cleaned_data = data_prep(cleaned_data)

# preparing text column
#word2vec_model = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin', binary=True)
#cleansed_text_data = prepare_text_col(word2vec_model, cleaned_data)
print("Data Cleansed")


#cleansed_text_data.to_csv('cleaned_text_data.csv', index = False)
cleansed_text_data = pd.read_csv('cleaned_text_data.csv')

# filling na got from word2vec processing , as all the words are not present in googles's pretrained model 
cleansed_text_data = cleansed_text_data.fillna(cleansed_text_data.min())

# making a copy of cleaned_data
#cleansed_text_data_cpy = cleansed_text_data.copy()

# creating traina nd test data from stitched data
train_data = cleansed_text_data[:ind]
test_data = cleansed_text_data[ind:]
train_data['salary'] = target
train_data[['salary_low', 'salary_upp']] = train_data.salary.str.split('to', expand=True)
train_data['salary_final'] = (train_data['salary_low'].astype(int) + train_data['salary_upp'].astype(int)) / 2
train_data.drop(columns =['salary', 'salary_low','salary_upp'], inplace = True)
test_data['salary_final'] = 0

# fetching all the column names
col = train_data.columns.tolist()

# scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_data = sc.fit_transform(train_data)
test_data = sc.transform(test_data)

# putting the scaled(numpy array) back into pandas data frame
train_data = pd.DataFrame(train_data, columns = col)
test_data = pd.DataFrame(test_data, columns = col)

# creating x_train, y_train and x_test
x_train = train_data.drop(columns=['salary_final'])
y_train = pd.DataFrame(train_data['salary_final'], columns=['salary_final'])
x_test = test_data

# with importance
imp_feat = find_feat_imp(x_train, y_train)
print("The features importance is calculated using random forest and they are : ", imp_feat)

# without feature importance fitting model
test_data_result_without_feat_imp = RF_regressor(x_train, y_train, x_test)

# with feature importance fitting model
x_train = train_data.drop(columns=['salary_final'])[['company_name_encoded', 'exp_upper','key_skills']]
y_train = pd.DataFrame(train_data['salary_final'], columns=['salary_final'])
x_test = test_data[['salary_final','company_name_encoded', 'exp_upper','key_skills']]
test_data_result_with_feat_imp = RF_regressor(x_train, y_train, x_test)

# writing the result back
test_data['salary_final'] = test_data_result_with_feat_imp['salary']
final_test_test = pd.DataFrame(sc.inverse_transform(test_data), columns = col)

final_test_test.to_csv("basic_rfr.csv", index = False)

Read Data
Data Stitched
Dropping job_type column
Data Cleansed

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_selection\from_model.py:196: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.estimator_.fit(X, y, **fit_params)

The features importance is calculated using random forest and they are :  ['company_name_encoded', 'exp_upper', 'key_skills']
14251 4751 14251 4751
RMSE of RF regressor on test set: 0.30

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.

RF Model Done
14251 4751 14251 4751
RMSE of RF regressor on test set: 0.31
RF Model Done

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.

In [257]:
train_data, test_data = read_data()
test_data['final'] = final_test_test['salary_final']
test_data.to_csv("result.csv", index = False)

,job_description,job_desig,key_skills,company_name_encoded,exp_lower,exp_upper,location_type_tier_one,location_type_tier_two
0,98.954875,27.129189,66.783257,3687,5,7,1,0
1,89.302073,25.153859,139.754841,458,10,17,0,1
2,36.771229,49.206624,85.322539,4195,5,9,1,0
3,119.615319,97.650627,160.857558,313,7,10,1,0
4,22.490385,73.567200,3.794169,1305,1,3,1,0
5,57.198336,22.272027,78.043950,4428,5,10,0,1
6,178.508786,9.415980,109.653982,1988,13,15,1,0
7,89.896163,31.503546,95.848751,1793,6,10,0,1
8,48.998594,7.542467,62.463533,3398,1,3,0,1
9,36.485654,145.791535,25.450742,3444,2,6,1,0
10,71.271744,51.862383,67.154408,3492,3,7,0,1
11,147.382106,0.468293,100.089826,1969,10,12,0,1
12,121.612899,14.796197,56.518480,3692,2,6,0,1
13,42.104461,99.774338,114.794332,4479,2,4,1,0
14,11.417075,35.690578,73.739752,2127,1,6,1,0
15,31.382346,88.028884,40.020481,2914,3,6,0,1
16,87.490955,174.556732,141.784289,3998,5,8,1,0
17,80.269280,30.679183,33.754336,1548,3,6,1,0
18,89.967109,61.233289,114.443628,2401,4,9,1,0
19,58.083152,13.034441,99.036725,4554,3,5,1,0
20,116.058345,15.402814,15.402814,3113,1,5,1,0
21,99.346012,152.933494,38.401214,1178,8,12,1,0
22,71.917013,168.383491,143.910098,1969,10,12,1,0
23,69.995141,74.565506,1.809668,2650,3,5,0,1
24,58.161049,121.938391,78.669056,4681,1,4,0,1
25,34.563603,79.599778,1.641166,4298,10,20,1,0
26,88.017767,8.212976,72.657395,895,3,7,0,1
27,7.259979,10.860558,53.999308,3063,3,5,1,0
28,88.017767,100.225782,156.773431,190,1,3,1,0
29,41.250104,23.515078,24.793400,2012,2,5,0,1
...,...,...,...,...,...,...,...,...
19772,70.990809,32.318560,20.761223,294,0,1,1,0
19773,80.208773,59.413206,70.865770,2621,18,25,0,1
19774,124.920414,92.198814,134.379132,2773,7,10,0,1
19775,88.017767,27.108067,36.655718,2094,1,5,1,0
19776,88.017767,84.575749,113.272073,269,0,1,1,0
19777,83.603902,12.506959,8.166169,1893,8,13,1,0
19778,82.144909,38.216616,65.439599,3319,9,11,1,0
19779,89.358717,28.897505,33.230302,1353,9,14,0,1
19780,71.228669,83.585358,89.040651,874,3,5,1,0
19781,15.450847,5.660439,55.213117,2829,2,5,0,1
19782,88.017767,38.037570,61.748683,3940,1,4,1,0
19783,62.953072,54.930409,NaN,3498,5,10,1,0
19784,73.300336,55.625216,58.014538,911,5,8,1,0
19785,76.520253,105.116556,12.893800,2365,7,10,1,0
19786,64.224886,49.775990,40.596941,1110,1,6,0,1
19787,10.388255,156.094162,33.770919,779,5,10,0,1
19788,167.902283,48.637583,4.014264,3188,1,6,0,1
19789,116.701468,182.784228,124.346946,1174,8,11,1,0
19790,86.402985,102.257694,29.658565,2036,1,6,1,0
19791,70.639682,11.179717,19.105353,1871,9,14,1,0
19792,42.253058,132.600816,190.386180,4272,5,10,0,1
19793,65.174182,250.767008,85.279501,1727,4,7,1,0
19794,80.700619,107.275740,131.545528,4384,7,12,0,1
19795,28.340373,53.821150,74.227357,173,3,6,0,1
19796,97.678316,41.732788,195.124902,838,1,3,0,1
19797,88.017767,82.092468,133.604992,2245,12,18,1,0
19798,88.017767,4.176096,63.529960,4966,0,3,0,1
19799,101.776637,59.252930,107.270882,4272,8,13,1,0
19800,75.170719,50.714923,83.754200,1793,1,3,0,1
19801,62.507524,93.306292,102.537726,1349,2,5,1,0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [34]:
train_data.head()

,job_description,job_desig,key_skills,company_name_encoded,exp_lower,exp_upper,location_type_tier_one,location_type_tier_two,salary_final
0,0.539402,-0.857405,-0.332922,0.885153,0.200576,-0.254879,0.740798,-0.740798,-0.443205
1,0.235725,-0.891027,1.175331,-1.302710,1.696628,2.105132,-1.349896,1.349896,0.021476
2,-1.416894,-0.481621,0.050267,1.229357,0.200576,0.217123,0.740798,-0.740798,0.795946
3,1.189379,0.342953,1.611503,-1.400957,0.798997,0.453124,0.740798,-0.740798,0.021476
4,-1.866169,-0.066975,-1.634845,-0.728811,-0.996266,-1.198883,0.740798,-0.740798,-0.804624

array([[ 0.53940219, -0.85740495, -0.33292157, ...,  0.74079787,
        -0.74079787, -0.44320528],
       [ 0.23572528, -0.89102739,  1.17533061, ..., -1.34989589,
         1.34989589,  0.02147636],
       [-1.41689379, -0.48162092,  0.05026749, ...,  0.74079787,
        -0.74079787,  0.79594575],
       ...,
       [ 0.08983994,  2.28831512, -0.02603695, ..., -1.34989589,
         1.34989589,  0.02147636],
       [-0.14558189, -0.78782877,  1.0536375 , ...,  0.74079787,
        -0.74079787, -0.80462433],
       [-0.71464085,  2.14091713,  0.07226881, ...,  0.74079787,
        -0.74079787,  0.02147636]])

RF Model Done

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.

In [163]:
from sklearn.linear_model import LinearRegression

In [169]:
def LR_regressor(x_train, y_train, x_test):
    from sklearn.linear_model import LinearRegression
    test_data_cpy = x_test.copy()
    feat = x_train.copy()
    target = y_train['salary_final']
    X,x,Y,y = train_test_split(feat,target,random_state=119)
    print(len(X),len(x),len(Y),len(y))
    regressor = LinearRegression()
    regressor.fit(x, y)
    y_pred = regressor.predict(x)
    from sklearn.metrics import mean_squared_error
    from math import sqrt

    rms = sqrt(mean_squared_error(y, y_pred))
    # Checking Accuracy on test set
    print('RMSE of LR regressor on test set: {:.2f}'.format(rms))
    # training on complete train set
    regressor = RandomForestRegressor(n_estimators = 100, random_state = 0) 
    regressor.fit(feat,target)
    y_test_pred = regressor.predict(x_test.drop(columns = ['salary_final']))
    test_data_cpy['salary'] = y_test_pred
    test_data_cpy['salary'].to_csv("submission_rfr.csv", index = False)  
    print("RF Model Done")
    return test_data_cpy